"""注册邀请码服务。

注册门控的两级机制：
- 安装码（setup code）：数据库中还没有任何用户时，首个注册者（即未来的
  管理员）必须提供。码在首次需要时生成并持久化到 KV，同时打印到启动日志
  与 8011 启动进度页（仅回环可达）——部署者在本机就能读到，局域网内其他
  设备读不到。没有它，新部署到户主注册之间的窗口期内任何人都能抢注成
  管理员（首用户即管理员的既有约定）。
- 邀请码（invite code）：已有管理员后，新成员注册必须持管理员生成的邀请
  码，一次性，用后作废，可主动吊销。注册从此默认关闭，"成员=家人"由
  管理员逐个拉入保证。

码存储走 KV 表（auth_setup_code / auth_invite_codes），随 SQLite 持久化，
不进 config.json（避免与配置读写锁纠缠）。
"""
from __future__ import annotations

import json
import logging
import secrets
import time

from ..core.database import Database
from ..core.exceptions import AppException

logger = logging.getLogger(__name__)

_KV_SETUP_CODE = "auth_setup_code"
_KV_INVITE_CODES = "auth_invite_codes"

# 去掉易混淆字符（0/O、1/I/L）的码表，8 位分两组，人工抄写不易错
_CODE_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"


def _generate_code() -> str:
    body = "".join(secrets.choice(_CODE_ALPHABET) for _ in range(8))
    return f"{body[:4]}-{body[4:]}"


def _normalize(code: str | None) -> str:
    """比较前归一化：去空白、统一大写。"""
    return (code or "").strip().upper()


async def _load_invites(db: Database) -> list[dict]:
    raw = await db.kv_get(_KV_INVITE_CODES)
    if not raw:
        return []
    try:
        data = json.loads(raw)
        return data if isinstance(data, list) else []
    except ValueError:
        logger.warning("invite codes KV corrupted, starting empty")
        return []


async def _save_invites(db: Database, invites: list[dict]) -> None:
    await db.kv_set(_KV_INVITE_CODES, json.dumps(invites, ensure_ascii=False))


async def get_setup_code(db: Database, generate: bool = True) -> str:
    """读取（必要时生成）安装码。生成只发生在还没有任何用户的阶段。

    每次生成都会打醒目日志——部署者最可能在此刻正盯着 `docker compose logs`。
    """
    existing = await db.kv_get(_KV_SETUP_CODE)
    if existing:
        return existing
    if not generate:
        return ""
    code = _generate_code()
    await db.kv_set(_KV_SETUP_CODE, code)
    logger.warning(
        "\n"
        "==============================================================\n"
        "  首次部署安装码: %s\n"
        "  首个注册用户（将成为管理员）需要在注册表单填入此码。\n"
        "  也可在启动进度页 http://localhost:8011/progress 查看。\n"
        "==============================================================",
        code,
    )
    return code


async def regenerate_setup_code(db: Database) -> str:
    """管理员重置安装码（用于怀疑泄露）。仅在没有用户时允许——已有管理员后
    安装码不再参与注册，重置无意义。"""
    if await db.user_count() > 0:
        raise AppException(
            "已有用户存在，安装码不再参与注册，无需重置",
            code="setup_code_not_applicable", http_status=409,
        )
    await db.kv_set(_KV_SETUP_CODE, "")
    # kv_set 不接受空串以外的语义区分，直接覆盖为新码
    code = _generate_code()
    await db.kv_set(_KV_SETUP_CODE, code)
    logger.warning("Setup code regenerated by admin (no users yet)")
    return code


async def verify_registration_code(db: Database, code: str, username: str = "") -> None:
    """注册门控校验。通过则静默返回（邀请码在此时标记已使用），失败抛 403。

    首用户阶段比安装码；之后比未使用的邀请码。码错误一律返回同一句话，
    不区分"不存在/已使用/已吊销"，避免给爆破者提供码状态侧信道。
    """
    if await db.user_count() == 0:
        setup = await get_setup_code(db, generate=True)
        if _normalize(code) != _normalize(setup):
            raise AppException(
                "需要有效的安装码才能完成首次注册（见部署日志或启动进度页）",
                code="registration_code_invalid", http_status=403,
            )
        return

    normalized = _normalize(code)
    if not normalized:
        raise AppException(
            "注册需要管理员生成的邀请码", code="registration_code_invalid", http_status=403,
        )
    invites = await _load_invites(db)
    now_ms = int(time.time() * 1000)
    for entry in invites:
        if _normalize(entry.get("code")) != normalized:
            continue
        if entry.get("revoked_at") or entry.get("used_at"):
            break
        entry["used_by"] = username
        entry["used_at"] = now_ms
        await _save_invites(db, invites)
        return
    raise AppException(
        "邀请码无效或已被使用", code="registration_code_invalid", http_status=403,
    )


async def create_invite(db: Database, created_by: str, note: str = "") -> dict:
    """管理员生成一枚一次性邀请码。"""
    entry = {
        "code": _generate_code(),
        "note": note.strip(),
        "created_by": created_by,
        "created_at": int(time.time() * 1000),
        "used_by": "",
        "used_at": 0,
        "revoked_at": 0,
    }
    invites = await _load_invites(db)
    invites.append(entry)
    await _save_invites(db, invites)
    logger.info("Invite code created by %s (note=%r)", created_by, entry["note"])
    return entry


async def list_invites(db: Database) -> list[dict]:
    """全量邀请码列表（管理页展示，含已用/已吊销状态）。"""
    return await _load_invites(db)


async def revoke_invite(db: Database, code: str) -> None:
    """吊销一枚未使用的邀请码。已使用的码吊销无副作用（幂等成功）。"""
    normalized = _normalize(code)
    invites = await _load_invites(db)
    for entry in invites:
        if _normalize(entry.get("code")) == normalized and not entry.get("revoked_at"):
            entry["revoked_at"] = int(time.time() * 1000)
            await _save_invites(db, invites)
            logger.info("Invite code revoked: %s", normalized)
            return
    raise AppException("邀请码不存在", code="invite_not_found", http_status=404)
