- id: 7dcd3306048e4cac8ba5c716b7b70d0c
  alias: Aether·关闭床头灯
  description: 每天晚上12点以后关闭床头灯
  triggers:
  - platform: time
    at: 00:00:00
  conditions: []
  actions:
  - action: aether_conversation.fire_rule
    data:
      rule_id: 77c640a1-4598-49bf-bbae-fcb07c511f5a
